version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=runnerz'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=santi'
    ports:
      - '5432:5432'

  app:
    image: runner-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/runnerz
      SPRING_DATASOURCE_USERNAME: santi
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"
